import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { useRouter } from "next/router";

const ItemView: NextPage = () => {
  const router = useRouter();
  const item = api.item.get.useQuery(
    {
      itemId: router.query.id as string,
    },
    {
      enabled: !!router.query.id,
    }
  );

  const itemData = item.data;

  if (!itemData) {
    return;
  }

  return (
    <>
      <Head>
        <title>View item</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col  gap-5 bg-gradient-to-b from-[#2e026d] to-[#15162c] p-4 text-white">
        <h2 className="mt-2 text-4xl">{itemData.name}</h2>
        <div className="container">
          <p>{itemData.description}</p>
          <p>{itemData.price}</p>
        </div>
      </main>
    </>
  );
};

export default ItemView;
