import { type Item } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { Card } from "~/components/Card";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const itemsList = api.item.itemsList.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col  gap-5 bg-gradient-to-b from-[#2e026d] to-[#15162c] p-4 text-white">
        <h2 className="mt-2 text-4xl">Items for sale</h2>
        <div className="container grid grid-cols-3 gap-5 ">
          {itemsList?.data?.map((item: Item) => (
            <Card key={item.id} item={item} />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
